/**
 * The demo file gallery for the hex inspector. Files live in public/demo/ and
 * are regenerated by scripts/make-demos.mjs (macOS); test/demos.test.ts keeps
 * this list, the files on disk, and the parsers in sync.
 */
export interface DemoFile {
  id: string
  label: string
  file: string
  desc: string
  /** How the gallery presents it: image = thumbnail, audio = inline player, file = download only. */
  kind: 'image' | 'audio' | 'file'
}

export const DEMO_GROUPS: { group: string; items: DemoFile[] }[] = [
  {
    group: 'images',
    items: [
      { id: 'png', label: 'PNG', file: 'demo.png', desc: 'Chunk chain with CRCs: IHDR → tEXt → pHYs → IDAT → IEND. A real 48×48 gradient.', kind: 'image' },
      { id: 'jpeg', label: 'JPEG', file: 'demo.jpg', desc: 'JFIF segments from sips: quantization tables, SOF0 dimensions, Huffman tables, entropy-coded scan.', kind: 'image' },
      { id: 'gif', label: 'GIF', file: 'demo.gif', desc: 'GIF87a: little-endian screen descriptor, global color table, LZW image data.', kind: 'image' },
      { id: 'bmp', label: 'BMP', file: 'demo.bmp', desc: 'DIB header variants, BGR order, rows padded to 4 bytes.', kind: 'image' },
      { id: 'icns', label: 'icns', file: 'demo.icns', desc: 'Apple icon made by iconutil: OSType-tagged entries with whole PNG files inside.', kind: 'image' },
    ],
  },
  {
    group: 'archives',
    items: [
      { id: 'zip', label: 'ZIP', file: 'demo.zip', desc: 'Three files + directories. Start at the END: EOCD → central directory → local headers.', kind: 'file' },
      { id: 'gzip', label: 'gzip', file: 'demo.txt.gz', desc: 'Header with original filename + mtime (FNAME flag), DEFLATE stream, CRC-32/ISIZE trailer.', kind: 'file' },
      { id: 'tar', label: 'tar', file: 'demo.tar', desc: 'POSIX ustar: 512-byte blocks, all numbers as octal ASCII text.', kind: 'file' },
      { id: 'xar', label: 'xar', file: 'demo.xar', desc: 'The macOS .pkg/.xip container: binary header, zlib-compressed XML table of contents, heap.', kind: 'file' },
      { id: 'dmg', label: 'DMG', file: 'demo.dmg', desc: 'Real hdiutil UDZO image — identified by the 512-byte koly block at the END of the file.', kind: 'file' },
    ],
  },
  {
    group: 'programs',
    items: [
      { id: 'elf', label: 'ELF', file: 'demo.elf', desc: 'A 170-byte static Linux x86-64 executable (write + exit syscalls). Copy it to Linux and it runs.', kind: 'file' },
      { id: 'pe', label: 'PE / EXE', file: 'demo.exe', desc: 'A 1 KiB Windows x64 console binary: MZ stub → PE32+ headers → one .text section (mov eax,42; ret).', kind: 'file' },
      { id: 'macho', label: 'Mach-O', file: 'demo.macho', desc: 'Real arm64 hello-world from clang: segments, dylib loads, LC_MAIN, code signature.', kind: 'file' },
      { id: 'class', label: 'Java class', file: 'Demo.class', desc: 'Real javac output: CAFEBABE, class-file version, constant pool.', kind: 'file' },
      { id: 'wasm', label: 'WASM', file: 'demo.wasm', desc: 'A 41-byte module exporting add(i32,i32) — paste into WebAssembly.instantiate and call it.', kind: 'file' },
    ],
  },
  {
    group: 'apple & data',
    items: [
      { id: 'bplist', label: 'binary plist', file: 'demo.plist', desc: 'Real plutil output: object graph, offset table, 32-byte trailer.', kind: 'file' },
      { id: 'appledouble', label: 'AppleDouble', file: 'apple-double.bin', desc: 'A genuine ._ file (via ditto): Finder info + extended attributes for a sidecar-less filesystem.', kind: 'file' },
      { id: 'sqlite', label: 'SQLite', file: 'demo.sqlite', desc: 'Real database with 512-byte pages: 100-byte header, sqlite_schema on page 1, an index B-tree.', kind: 'file' },
      { id: 'pdf', label: 'PDF', file: 'demo.pdf', desc: 'Minimal but complete: 5 objects, a correct xref table, trailer. It opens and says hello.', kind: 'file' },
    ],
  },
  {
    group: 'media',
    items: [
      { id: 'wav', label: 'WAV', file: 'demo.wav', desc: 'RIFF/WAVE: the fmt chunk is the decoder contract. A playable 440 Hz beep.', kind: 'audio' },
      { id: 'm4a', label: 'MP4 / M4A', file: 'demo.m4a', desc: 'Real AAC from afconvert in an ISO-BMFF box tree: ftyp brand, moov metadata, mdat.', kind: 'audio' },
    ],
  },
]

export const ALL_DEMOS: DemoFile[] = DEMO_GROUPS.flatMap((g) => g.items)
